### ISSUE TITLE
Addon (homebridge) container DNS problems

### ISSUE THREAD

**Issue by demslob** [home-assistant/hassio#520] opened 2018-06-21 14:47 UTC
When I try to add "packages" to my homebridge addon I get an error

[cont-init.d] 80-user-packages.sh: executing... 
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: temporary error (try again later)

I think the problem is in DNS inside containers

my host /etc/resolv.conf is
nameserver 127.0.1.1

In host dig command from 127.0.1.1 works and shows DNS records

additional info:

root@hass:/home/hass# docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
9f223eda725e        hassioaddons/homebridge-i386           "/init"                  4 seconds ago       Up 1 second                             addon_a0d7b954_homebridge
52c679f166a1        homeassistant/qemux86-homeassistant    "python3 -m homeas..."   7 minutes ago       Up 7 minutes                            homeassistant
063a78642f9a        homeassistant/i386-hassio-supervisor   "python3 -m hassio"      23 minutes ago      Up 8 minutes                            hassio_supervisor

root@hass:/home/hass# docker exec -i -t homeassistant cat /etc/resolv.conf
nameserver 172.30.32.2
options ndots:0

root@hass:/home/hass# docker exec -i -t hassio_supervisor cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0

root@hass:/home/hass# docker exec -i -t addon_a0d7b954_homebridge cat /etc/resolv.conf
nameserver 172.30.32.2
options ndots:0

Stopping apparmor didn't help me

**Comment by pvizeli** [comment] 2018-06-21 15:09
```
my host /etc/resolv.conf is
nameserver 127.0.1.1
```
^
Do you have a local dns server on your system? Try to use 8.8.8.8 as first dns server. Docker have a bit problem with some kinds of dns setups. I try to fix that with a new dns system in a next supervisor.

**Comment by demslob** [comment] 2018-06-21 15:16
It is default Ubuntu desktop dnsmasq.
I have added 8.8.8.8 to /etc/resolvconf/resolv.conf.d/head.
Now my host /etc/resolv.conf is
nameserver 8.8.8.8
nameserver 127.0.1.1

I have also added {"dns": ["8.8.8.8"]} to /etc/docker/daemon.json

still same issue

root@hass:/home/hass# systemctl restart docker
root@hass:/home/hass# docker exec -i -t homeassistant cat /etc/resolv.conf
nameserver 172.30.32.2
options ndots:0
root@hass:/home/hass# docker exec -i -t homeassistant /bin/bash 
bash-4.4# ping google.com
ping: bad address 'google.com'

**Comment by demslob** [comment] 2018-06-21 15:20
future: <Task finished coro=<DNSForward.stop() done, defined at /usr/lib/python3.6/site-packages/hassio/misc/dns.py:34> exception=ProcessLookupError()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/hassio/misc/dns.py", line 40, in stop
    self.proc.kill()
  File "/usr/lib/python3.6/asyncio/subprocess.py", line 138, in kill
    self._transport.kill()
  File "uvloop/handles/process.pyx", line 613, in uvloop.loop.UVProcessTransport.kill
  File "uvloop/handles/process.pyx", line 360, in uvloop.loop.UVProcessTransport._check_proc
ProcessLookupError

**Comment by pvizeli** [comment] 2018-06-21 15:21
Version of supervisor?

**Comment by demslob** [comment] 2018-06-21 15:22
107

**Comment by demslob** [comment] 2018-06-21 15:31
Docker version 1.13.1, build 092cba3

**Comment by demslob** [comment] 2018-06-21 16:14
Now my supervisor updated to 108
Still, don't understand why homeassistant and homebridge are getting different DNS than other conatiners
root@hass:/home/hass# docker exec -i -t addon_a0d7b954_homebridge cat /etc/resolv.conf
nameserver 172.30.32.2
options ndots:0
root@hass:/home/hass# docker exec -i -t addon_core_duckdns cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
root@hass:/home/hass# docker exec -i -t addon_core_configurator cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0
root@hass:/home/hass# docker exec -i -t homeassistant cat /etc/resolv.conf
nameserver 172.30.32.2
options ndots:0
root@hass:/home/hass# docker exec -i -t hassio_supervisor cat /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0

**Comment by pvizeli** [comment] 2018-06-22 07:28
> Docker version 1.13.1, build 092cba3

This version is not suppoted, we support only CE > 17.06.0

**Comment by frenck** [comment] 2018-09-20 20:31
Closing this issue, since it is caused by an older Docker version.

**Closed by frenck** 2018-09-20 20:31 UTC
Labels: Old docker
