### ISSUE TITLE
Update fails: no such image: homeassistant/raspberrypi3-homeassistant

### ISSUE THREAD

**Issue by fekberg** [home-assistant/hassio#420] opened 2018-03-22 21:20 UTC
While trying to run `hassio ha update` I receive the following error:

> Can't install homeassistant/raspberrypi3-homeassistant:0.65.6 -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi3-homeassistant:0.65.6: No such image: homeassistant/raspberrypi3-homeassistant:0.65.6").

Obviously it also fails through the UI.

`df -h` shows me the following:

```
core-ssh:/backup# df -h
Filesystem                Size      Used Available Use% Mounted on
none                     56.9G      5.3G     48.7G  10% /
tmpfs                   486.1M     84.0K    486.0M   0% /dev
tmpfs                   486.1M         0    486.1M   0% /sys/fs/cgroup
/dev/mmcblk0p3          294.1M    216.7M     61.9M  78% /dev/init
/dev/mmcblk0p6           56.9G      5.3G     48.7G  10% /backup
/dev/mmcblk0p6           56.9G      5.3G     48.7G  10% /share
/dev/mmcblk0p6           56.9G      5.3G     48.7G  10% /data
/dev/mmcblk0p6           56.9G      5.3G     48.7G  10% /config
/dev/mmcblk0p6           56.9G      5.3G     48.7G  10% /ssl
/dev/mmcblk0p6           56.9G      5.3G     48.7G  10% /addons
/dev/mmcblk0p6           56.9G      5.3G     48.7G  10% /etc/resolv.conf
/dev/mmcblk0p6           56.9G      5.3G     48.7G  10% /etc/hostname
/dev/mmcblk0p6           56.9G      5.3G     48.7G  10% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   486.1M     84.0K    486.0M   0% /proc/timer_list
tmpfs                   486.1M     84.0K    486.0M   0% /proc/timer_stats
tmpfs                   486.1M     84.0K    486.0M   0% /proc/sched_debug
tmpfs                   486.1M         0    486.1M   0% /sys/firmware
```

Docker versions:
homeassistant/armhf-hassio-supervisor: 0.98
homeassistant/raspberrypi3-homeassistant: 0.60.1

From what I can tell, there's plenty of space for the upgrade to use. So why is this failing?

**Comment by GaryOkie** [comment] 2018-03-23 16:52
I reported the exact issue immediately before yours - #419 .   There are many reports of this exact same issue in Reddit, HA Forum, and GitHub.    The only solution I've seen is to use a larger SDCard (if using a Raspberry), but clearly yours is already quite large with more than ample space  (~49Gb).   Oh, a complete from scratch rebuild can also solve the problem, but who wants to do that?  

I will switch to OpenHab if I am required to rebuild Hassio from scratch in order to solve this.   Heck, I can't even update small components SSH or DuckDNS, and get this same error.  Even trying to rebuild from a snapshot fails, so that's a useless backup.

I'm guessing the partition where the image is downloaded/extracted (docker partition?)  is full.   There are no tools in HASSIO that I know of that allow you to view or manage these underlying OS/Docker partitions if they need some housecleaning.   I've submitted an enhancement request related to this.

I hope we get lucky and someone knowledgeable responds to this with helpful advice.

**Comment by kajmaj** [comment] 2018-03-31 20:17
I have the same problem.
Rebuild from scratch is impossible -  because "system" cannot install 0.66.0
Platform: Raspberry Pi3 B
System: ResinOS , 1.1 and 1.3, does not matter which one
Snapshots are useless, backups as well.

**Comment by pvizeli** [comment] 2018-04-03 09:21
Maybe a network problem? The error message is not realy exactly from docker :(

**Comment by fekberg** [comment] 2018-04-03 09:23
Network works great, so that's not the issue. I completely re-installed and moved over to docker on a server instead of RPi.

**Comment by pvizeli** [comment] 2018-04-03 09:29
The supervisor try a `docker pull` in background over the docker API, and they return a error that the image is not found. This error is happening:
- Diskspace full
- Proxy problem
- DNS server not working they comes from DHCP
- Time is out of sync

**Comment by fekberg** [comment] 2018-04-03 10:23
As I can't reproduce this, and my installation is trashed, maybe close the issue? Or do you want to keep it open for others with the same issue?

**Comment by bliemli** [comment] 2018-04-03 12:42
@pvizeli No, you managed to remove the `latest` tag from the repositories which docker uses by default.

**Comment by GaryOkie** [comment] 2018-04-03 17:30
As I received no assistance with this error for well over a week, I ended up starting from scratch  rebuilding Hassio.   I sure didn't want to do that, but updates are working perfectly now.   Heck of a way to "solve" it.

Funny that my issue was reported before this one and was closed as a duplicate.   Oh well,  I'm glad to see it was finally getting some attention.   Not sure what this "latest" tag removal is about, but I can state that no messing around with any internal files were done, and that there were no DNS/network problems.

**Comment by igormages** [comment] 2018-06-15 18:07
Same problem... :(

**Comment by robin13** [comment] 2018-10-22 09:31
Same problem with upgrade from 0.78.0 -> 0.80.3

```
18-10-22 08:03:31 INFO (MainThread) [hassio.api.security] /homeassistant/update access from core_ssh
18-10-22 08:03:33 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.80.3
18-10-22 08:03:33 INFO (SyncWorker_0) [hassio.docker.interface] Update Docker 0.78.0 with homeassistant/raspberrypi-homeassistant:0.80.3
18-10-22 08:03:33 INFO (SyncWorker_0) [hassio.docker.interface] Pull image homeassistant/raspberrypi-homeassistant tag 0.80.3.
18-10-22 08:03:47 ERROR (SyncWorker_0) [hassio.docker.interface] Can't install homeassistant/raspberrypi-homeassistant:0.80.3 -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi-homeassistant:0.80.3: No such image: homeassistant/raspberrypi-homeassistant:0.80.3").
18-10-22 08:03:51 WARNING (MainThread) [hassio.homeassistant] Home Assistant is already running!
18-10-22 08:03:51 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.80.3
```

**Comment by Gio76** [comment] 2018-10-24 15:05
**Home Assistant release with the issue:**
0.80.3

**Last working Home Assistant release (if known):**
0.80.2

**Operating environment (Hass.io/Docker/Windows/etc.):**
- Hass.io on a Raspberry Pi 3 Model B (32gb SD)
- Hass.io supervisor 138
- HassOS 1.11

**Description of problem:**
Same problem with upgrade from 0.80.3 -> 0.81.0b1

**Traceback (if applicable):**
```
18-10-24 14:58:21 ERROR (SyncWorker_6) [hassio.docker.interface] Can't install homeassistant/raspberrypi3-homeassistant:0.81.0b1 -> 404 Client Error: Not Found ("manifest for homeassistant/raspberrypi3-homeassistant:0.81.0b1 not found").
18-10-24 14:58:21 WARNING (MainThread) [hassio.homeassistant] Home Assistant is already running!
18-10-24 14:58:21 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.81.0b1
```

**Comment by juliank** [comment] 2018-10-28 21:59
> Same problem with upgrade from 0.78.0 -> 0.80.3
> 
> ```
> 18-10-22 08:03:31 INFO (MainThread) [hassio.api.security] /homeassistant/update access from core_ssh
> 18-10-22 08:03:33 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.80.3
> 18-10-22 08:03:33 INFO (SyncWorker_0) [hassio.docker.interface] Update Docker 0.78.0 with homeassistant/raspberrypi-homeassistant:0.80.3
> 18-10-22 08:03:33 INFO (SyncWorker_0) [hassio.docker.interface] Pull image homeassistant/raspberrypi-homeassistant tag 0.80.3.
> 18-10-22 08:03:47 ERROR (SyncWorker_0) [hassio.docker.interface] Can't install homeassistant/raspberrypi-homeassistant:0.80.3 -> 404 Client Error: Not Found ("no such image: homeassistant/raspberrypi-homeassistant:0.80.3: No such image: homeassistant/raspberrypi-homeassistant:0.80.3").
> 18-10-22 08:03:51 WARNING (MainThread) [hassio.homeassistant] Home Assistant is already running!
> 18-10-22 08:03:51 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.80.3
> ```
Also same problem (and same log content) when trying to upgrade from 0.78.3 -> 0.81.0

**Comment by Grepsy** [comment] 2018-10-29 12:14
I've done a clean (first) install and also run into this issue. It seems the docker images has no connectivity. I'm surprised this throws a `404 Client Error`, which would indicate the webserver actually returned a Not Found. This logging is pretty misleading if you ask me.

**Comment by nmpnmp** [comment] 2018-11-05 00:57
Seeing the same problem for the past four days, up to and including release 81.6.

Worrying that this has been going on since the start of this year, on and off. I hope its not as simple as a missing tag on a docker image. 

Raised this on the HA forums, and got absolutely no help there either.

@pvizeli @bliemli Could you please advise?

**Comment by robin13** [comment] 2018-11-09 12:57
Strangely for me today with the update to 0.81.6 it worked... I haven't changed anything on Hassio...

**Comment by frenck** [comment] 2019-01-01 12:57
404 has many reasons, but are mainly out of our control/scope.
As listed by @pvizeli, they are mainly caused by:

- Disk space full (or not enough to download, unpack and install).
- Proxy problem.
- DNS server not working / providers wrongful information.
- Time is out of sync.

For now I'm closing this issue.

**Closed by frenck** 2019-01-01 12:57 UTC
