### ISSUE TITLE
How to set local addon state to "unprotected"?

### ISSUE THREAD

**Issue by tomcatGu** [home-assistant/hassio#666] opened 2018-08-25 14:02 UTC
In config.json file I use the following config:
  "full_access": true,
  "protected": false
But no effect.

**Comment by frenck** [comment] 2018-08-30 17:44
This is currently not yet possible.
Unprotected is an action that a user could do, not an add-on. This gives the user the awareness and specific choice of "unprotecting" an add-on. This part is not yet added to the user's Hassio/add-on panel.

**Comment by frenck** [comment] 2018-08-30 18:01
Duplicate of #664

**Closed by frenck** 2018-08-30 18:01 UTC

**Comment by pergolafabio** [comment] 2021-02-23 05:44
Hi @frenck , is this now possible? I also want full access to retrieve all devices...how can I disable protection mode on a local add-on?

@tomcatGu , did you manage?
