### ISSUE TITLE
Does not install on Linux

### ISSUE THREAD

**Issue by MarcFinns** [home-assistant/hassio#851] opened 2018-12-09 09:21 UTC
**Home Assistant release with the issue:**

**Home Assistant release with the issue:**

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

**Description of problem:**
Hello, I want to use hassio in my new house and i added a new VM with Ubuntu 18.04.1 to my home server. I followed the [installation instructions](https://github.com/home-assistant/hassio-build/tree/master/install#install-hassio) and the system is stuck at "preparing hass.io".
In the logs of the hassio supervisor I see the entry below, repeating forever. I shall assume the install procedure has issues. I found other references to the same by googling around, no solutions though.
How to fix it? Thanks 

18-12-09 09:11:02 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
18-12-09 09:11:02 INFO (MainThread) [hassio.core] Hass.io is up and running
18-12-09 09:11:02 INFO (MainThread) [hassio.homeassistant] Setup Home Assistant
18-12-09 09:11:02 INFO (SyncWorker_2) [hassio.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.83.3.
**18-12-09 09:11:50 ERROR (SyncWorker_2) [hassio.docker.interface] Can't install homeassistant/qemux86-64-homeassistant:0.83.3 -> 404 Client Error: Not Found ("no such image: homeassistant/qemux86-64-homeassistant:0.83.3: No such image: homeassistant/qemux86-64-homeassistant:0.83.3").**
18-12-09 09:11:50 WARNING (MainThread) [hassio.homeassistant] Error on install Home Assistant. Retry in 60sec

**Comment by cbrherms** [comment] 2018-12-12 20:34
This might be due to an Ubuntu 18.04 / docker DNS related issue, or at least i had a similar issue when installing on 18.04 due to a change Ubuntu had made.
If you can console in to the supervisor container, does `nslookup dockerhub.com` succeed?
If not, one potential fix here: https://github.com/docker/libnetwork/issues/2187#issuecomment-413351987

**Comment by frenck** [comment] 2019-01-01 12:59
404 has many reasons, but are mainly out of our control/scope.
It is mainly caused by any of the following:

- Disk space full (or not enough to download, unpack and install).
- Proxy problem.
- DNS server not working / providers wrongful information.
- Time is out of sync.

For now, I'm closing this issue, feel free to re-open if the problem persists.

**Closed by frenck** 2019-01-01 12:59 UTC

**Comment by MarcFinns** [comment] 2019-01-01 13:08
FYI issue went away on its own as soon as a new version came out. As I did not change anything in the VM, I assume it was a bug. Perhaps updates were working fine but fresh installs didn’t. Happy ny
