### ISSUE TITLE
Feature Request: Show the /dev/serial/by-id/xxx paths in the list from the "Hardware" button

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/hassio#1111] opened 2019-06-03 19:54 UTC
**Home Assistant release with the issue:**

0.93.1

**Operating environment (HassOS/Generic):**

Generic Ubuntu

**Supervisor logs:**

**Description of problem:**

There are lots of reports in Discord and in the forums about users suddenly losing their whole Z-Wave network and it's almost always due to the dev node changing for some reason.  Users will set up their Z-Wave dongle at /dev/ttyACM0, the default after booting up, and it'll change to /dev/ttyACM1 for some reason without a reboot.  Users then freak out (I was guilty of this the first time), and if they're smart, will try to change the device in the .storage/core.config_entries file to /dev/ttyACM1 or some other random choice to try to find it again.  This often fails because they forgot to stop Home Assistant, so it just reverts back to the original name.

A better solution in a Linux-based environment is to use the /dev/serial/by-id/xx path corresponding to the dongle, which is a link to the dev node that's currently assigned to the device.  It's easier to pick the right entry because it usually has useful text describing the device and it will *always* point to that device.

The problem is that those /dev/serial/by-id/xxx nodes are not listed in the "Hardware" list in Hass.io, and they're not visible from the SSH add-on.  The user either has to open a shell in the homeassistant docker container or somehow get to the console to see which nodes are available and copy/paste the right one.  That's easier if you're running Hass.io on Ubuntu, for instances, but it's quite a hassle for new users running HassOS.

I recommend including all entries in /dev/serial/by-id/xxx to make the user aware of them and to encourage them to use them, rather than pointing to the ephemeral /dev/ttyACMx nodes.

**Comment by lenisko** [comment] 2019-06-19 15:08
Almost every reboot and I need to swap path to zwave, zigbee.
Would be really great to match them by ID.

I hope this issue will get some attention.

**Comment by lenisko** [comment] 2019-06-26 00:07
Merged in master, big thanks for @pvizeli help on this!

**Comment by rccoleman** [comment] 2019-06-26 00:09
Saw the tweet :). Thanks, Pascal!

**Comment by pvizeli** [comment] 2019-06-26 07:45
Thanks also @lenisko for discovery it. Hope I see more contributions :D

**Closed by pvizeli** 2019-06-26 07:45 UTC

**Comment by kpine** [comment] 2019-07-01 23:51
There were already two issues tracking this problem, #867 and #911. Can those be closed now? Lots of people watching those and I'm sure they'd like to know if the problem is finally fixed.

**Comment by rccoleman** [comment] 2019-07-01 23:53
Wow, my search efforts were clearly lacking when I filed this issue :). I think that both can be closed now.
