### ISSUE TITLE
Running addons with --privileged

### ISSUE THREAD

**Issue by pschmitt** [home-assistant/hassio#201] opened 2017-09-27 18:18 UTC
Hi.

I'm trying to create an addon for [pilight](https://www.pilight.org/): https://github.com/pschmitt/hassio-addons/tree/master/pilight
Unfortunately for this to work I'd need to run the container with `--privileged`. AFAIK this is not possible right now. This and `--pid=host` may be useful for other addons as well (dind, zabbix-agent)

**Comment by gollo** [comment] 2017-09-27 18:53
Is the device mapping in config.json (eg ```"devices": [ "/dev/vchiq:/dev/vchiq:rwm" ]```) not sufficient?

**Comment by pschmitt** [comment] 2017-09-27 19:20
No. I tried both with `--device /dev/mem:/dev/mem:rw` and `--cad_add SYS_RAWIO`. The service starts okay, I can connect to it and all but nothing happens when I connect ask the daemon to issue commands (they are logged as successful - but that's all). Something else must be missing since starting the container with `--privileged` makes it work as expected.

If you happen to have a RF transmitter you can try it for yourself:

```bash 
# Do not work
docker run -it --rm --name pilight --device /dev/mem --cap-add SYS_RAWIO pschmitt/hassio-addon-armhf-pilight
docker exec -it pilight pilight-send -p pollin -u 1 -s 1 -t
# Works
docker run -it --rm --name pilight --privileged pschmitt/hassio-addon-armhf-pilight
docker exec -it pilight pilight-send -p pollin -u 1 -s 1 -t

**Comment by gollo** [comment] 2017-09-27 19:34
Sure. I guess the next question is why this is an addon and not just a component/platform in main HA (which runs with ```--privileged```). I suppose I'm just establishing a definitive requirement to then base the discussion on.  I'm assuming the default position is to avoid having to do this if at all possible (so a 3rd party addon doesn't kill the the entire appliance), but others know more/better than me...

**Comment by pschmitt** [comment] 2017-09-27 19:44
I guess pilight *could* be implemented as a component, but that is a ton of work: just take a look at the [source code](https://github.com/pilight/pilight). 
There already is a client component in hass. But nah - why not just use it?

Anyway this `--privileged` requirement will certainly come up for other addons. Like for example `zabbix-agent`. Ideally the agent would need to run with `--privileged` *and* `--pid=host` which is not available to addons as well.

**Comment by pvizeli** [comment] 2017-09-27 23:13
For zabbix and official docs (https://hub.docker.com/r/zabbix/zabbix-agent/)
`docker run --name some-zabbix-agent -v /dev/sdc:/dev/sdc -d zabbix/zabbix-agent:latest`

Privileged is only a other word for "I don't know what he need so I give him all right". So we have no privileged options for addon while we work with capability (like capsh can help). At the moment we support 3 but If you need some one, we can add this. That allow us later to give a user a hint what the addon can do on his system.
https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
http://man7.org/linux/man-pages/man7/capabilities.7.html

You need only find the correct cap to run inside docker.

For host pid I will look. We need find a mix that a addon can not damage a system and protect the user and give him aware for addons vs. development of add-ons.

**Comment by pvizeli** [comment] 2017-09-27 23:18
For good debain multiarch image look into this:
https://github.com/home-assistant/hassio-addons/blob/master/google_assistant/build.json

**Comment by pschmitt** [comment] 2017-09-28 05:55
@pvizeli You missed the "Privileged mode" paragraph in the official documentation of zabbix-agent you linked: https://hub.docker.com/r/zabbix/zabbix-agent/

> By default, Docker containers are "unprivileged" and do not have access to the most of host resources. Zabbix agent is designed to monitor system resources,

**Comment by gollo** [comment] 2017-09-28 06:37
Perhaps a clearer definition of what hassio (and perhaps moreso, addons) is intended to do is required (or may exist, I can't find anything right now).  IMHO, hassio is used to create an **appliance**, plug and play, all user friendly and everything happens automatically (eg updates, including the OS) or via the web interface.  Anything that can potentially break this has to be closely controlled/limited, hence the restrictions on addons. Really the hassio box is just homeassistant, and whatever helpers it may need to talk to the outside world, not also a monitoring hub/server (but maybe a client of that, yes.) 

I think the zabbix use case isn't really a hassio one.  I think you would be better off using standalone homeassistant on a "normal" OS and run zabbix alongside of it, if you desire to host both on the same machine. For now this seems the same would be the best approach for pilight as well (I think it would be great for homeassistant to have closer integration with this, but an add-on for hassio probably isn't the answer.
Maybe @pvizeli can help clarify the hassio scope/vision.  @pschmitt you've got the discussion you wanted :-)

**Comment by pvizeli** [comment] 2017-09-28 09:12
@pschmitt `privileged or you may mount some system-wide volumes` I think the `or` have a big ident here. That mean you can add `/dev/sdc:/dev/sdc:rwm` to your device lists and it will work like you give `privileged` access.

Same with pilight, if you know with cap he need (I think SYS_ADMIN) it will be run. The Problem is with privileged Modus it is a very bad praxtic. In some case it could be make sense but it also destroy any things that will be docker stand for it.

I think this discusion is very imported and I'm happy to read other opinions.

**Comment by pschmitt** [comment] 2017-09-28 09:50
I'd suggest the following: implement `--privileged` but show a big red warning on the addon page with a corresponding message. "Please contact the developer. Running privileged addons is strongly discouraged"

**Comment by pvizeli** [comment] 2017-09-29 10:21
https://github.com/moby/moby/issues/25885

I add a new options `gpio` to config to allow access to gpio interface with sys but we give not the hole sys free to docker, that is very danger.

I think we should go out at evening with that update and you can use pilight as add-on :+1:

**Comment by pvizeli** [comment] 2017-09-29 20:24
0.65 with gpio support is out

**Comment by pschmitt** [comment] 2017-09-29 20:27
Nice

**Comment by pschmitt** [comment] 2017-09-29 21:36
Thanks for the reactivity @pvizeli. The bad news is that pilight seems to require broader access to `/sys`. I have no idea what it may be using on there. But /sys/class/gpio simply isn't enough :(

**Comment by pvizeli** [comment] 2017-09-29 23:17
Do you run it with /dev/mem and SYS_RAWIO?

/sys/devices/virtual/gpio was the old place of gpio interface on linux kernel 3.x

**Comment by pvizeli** [comment] 2017-09-30 06:54
Can you try that? Also what he need on devices. So I can make a better solution.

For privileged modues. I see PR for docker they will merged in next ce release and dedicate the privileged mode. They switch to a preset like system. I think we can do the same now and defined presets they have the access where we need.

**Comment by pschmitt** [comment] 2017-09-30 06:55
Works:
`docker run -it --rm --cap-add SYS_RAWIO --device /dev/mem -v /sys:/sys --name pilight pschmitt/hassio-addon-armhf-pilight`

Does not:
`docker run -it --rm --cap-add SYS_RAWIO --device /dev/mem -v /sys/class/gpio:/sys/class/gpio --name pilight pschmitt/hassio-addon-armhf-pilight`

I'll try to figure out what is needed

**Comment by pschmitt** [comment] 2017-09-30 07:02
Got it! It's `/sys/devices/platform/soc`

`docker run -it --rm --cap-add SYS_RAWIO --device /dev/mem -v /sys/cla/gpio -v /sys/devices/platform/soc:/sys/devices/platform/soc --name pilight pschmitt/hassio-addon-armhf-pilight`

**Comment by pvizeli** [comment] 2017-09-30 07:42
Okay. I will not make it hard to implement things like this. I will add a user-friendly or developer friendly access system.


https://github.com/raspberrypi/linux/issues/1117

I make fix and release it in 3-4 hours. Thanks to help for make it better.

**Comment by pvizeli** [comment] 2017-09-30 08:01
Short question for your monitor software problem. Do work:
`-v /dev:/dev:ro`

**Comment by pschmitt** [comment] 2017-09-30 08:33
Bind-mounting `/dev` would have a ton a side-effects since this is a special dir, both for the host and the container. It'd certainly break `/dev/stdin` and `/dev/stdout` since these are supposed to be writable.

I tried that nonetheless and as expected the container didn't even start:
```
root@hassistant:~# docker run -it --rm -v /dev:/dev -p 10056:10050 --cap-add SYS_ADMIN pschmitt/hassio-addon-armhf-zabbix-agent
docker: Error response from daemon: invalid character 'c' looking for beginning of value.
```

**Comment by pvizeli** [comment] 2017-09-30 08:41
I speak with paulus and we add a user device selector for add-ons. That will be control over API. I hope we find a UI developer that have time to make that nice on it.

That make you able to modify the device list dynamic. So you can provide a add-on with basic and imported devices for runtime. Later can the user also add more device (in your case for monitoring) that he want to control with it.

But I look too for more solutions

**Closed** 2019-04-23 15:59 UTC
Labels: wontfix

**Comment by GabrielePicco** [comment] 2020-03-15 12:21
I have the same problem with a [Wireguard client add-on](https://github.com/GabrielePicco/home-assistant-wireguard-client-addon) that i trying to build. Any idea on how to solve it ?

For the Wireguard client the problem is: `Setting key "net.ipv6.conf.default.forwarding": Read-only file system`.
I have in the configuration
  ```
"kernel_modules": true,
"full_access": true, 
```

**Comment by frenck** [comment] 2020-03-16 09:09
You can't do that @GabrielePicco, as was already discussed above.
Furthermore, this issue has been closed for 11 months already. Please don't drag up old issues, instead, just create new ones.

Thanks!

**Comment by GabrielePicco** [comment] 2020-03-16 16:18
I know I can't run an add-on with --privileged. But it seemed pertinent to the discussion for the alternative solutions proposed in this issue. In any case, I will specify it better in the new issue.

Thanks
