### ISSUE TITLE
Issues to access local addons starting with Supervisor Version 174

### ISSUE THREAD

**Issue by kolossboss** [home-assistant/hassio#1230] opened 2019-08-16 20:21 UTC
**Home Assistant release with the issue:**
0.97.2

**Operating environment (HassOS/Generic):**
hassio Docker on Ubuntu Server

**Description of problem:**

Its not possible to connect to some addons like (**glances** and **portainer**) with a local IP and a manuell port. (the login dialog appears, but its not possible to login) 
Ingress working fine.
Also setting up MariaDB is not working to. Got this error messages in the log.

`Error during connection setup: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'core-mariadb' (115)")
(Background on this error at: http://sqlalche.me/e/e3q8) (retrying in 3 seconds)`

If I downgrade the Supervisor to Version 173 everything starts working again for a shot peroid of time, because the supervisor upgrade again to 179 after a few seconds.

**Comment by MorpheusRO** [comment] 2019-08-16 23:29
I have the same issues!
My HA is unusable... :(

**Comment by frenck** [comment] 2019-08-18 11:40
Duplicate of #1231

**Closed by frenck** 2019-08-18 11:40 UTC

**Comment by kolossboss** [comment] 2019-08-18 19:56
I'm sorry. All of my issues still exists on Version 180 :-(
I dont now whats wrong. I cant connect local via IP and Port to the addons (glances, portainer....) and MariaDB is also still not working.

The CLI command: `hassio dns Info` shows
- dns://8.8.8.8
- dns://1.1.1.1

should this not `9.9.9.9` because of Quad9?

**Comment by MorpheusRO** [comment] 2019-08-19 02:52
> MariaDB Addon still not working.

I managed to make MariaDB work again, by uninstalling and re-installing the addon.
I lost the history, but at least is working again.
