### ISSUE TITLE
Persistent USB names

### ISSUE THREAD

**Issue by robhuls** [home-assistant/hassio#261] opened 2017-11-27 19:06 UTC
I have an RFXTRX device and a DSMR device. Both connect over USB, one gets the name ttyUSB0 and the other ttyUSB1. The DSMR and RFXTRX are arbitrarily named ttyUSB0 or 1, because the names are not persistent when HAS is restarted (thus, at least every time HAS is updated). I used to fix this with a udev rule, but I don't think this is possible in hassio. This thus effectively breaks all installations that have two or more devices using ttyUSBX. See also:
https://community.home-assistant.io/t/persistant-usb-names/31500

**Comment by Emacee** [comment] 2017-12-13 00:19
I’m interested in a solution for this problem as wel, same dual USB setup but than with DSMR and RFLink gateway (works faster over usb than WiFi). I wonder whether the 0.76 update addresses this.

**Comment by jonand** [comment] 2017-12-13 05:28
My z-stick kept moving between `/dev/ttyACM0` and `/dev/ttyACM1` on reboot and I couldn't manage to write an udev rule due to the hassio read only file system (it might be possible through the dbus?).

I managed to achieve persistent usb naming by setting the `zwave: usb_path` to `/dev/serial/by-id/the-usb-id` instead of `/dev/ttyACMx`.

**Comment by robhuls** [comment] 2017-12-13 18:10
@jonand how did you find out what to use for 'the-usb-id'. I have seen similar links before, but in hassio I cannot find /dev/serial.

**Comment by jonand** [comment] 2017-12-13 20:28
@robhuls `/dev/serial` is visible if you [ssh into the host](https://home-assistant.io/developers/hassio/debugging/).

**Comment by robhuls** [comment] 2017-12-17 13:20
@jonand Thanks! A bit cumbersome for a 'standard' procedure, but it keeps my installation from breaking every few restarts!

**Comment by marcgarciamarti** [comment] 2018-02-03 22:20
I second this. Every time I reboot hassio, I must fiddle around with ACM. That is annoying. I hope it can be fixed in further releases.

**Comment by aronsjoberg** [comment] 2018-04-06 11:25
What command do I need to find out what USB devices are connected to the Rpi3 (so I can use the long /dev/serial-path instead of the short path which changes after reboot)?

**Comment by deisi** [comment] 2018-04-29 10:54
> I hope it can be fixed in further releases.

I think the random changing between `/dev/ttyACM0` to `/dev/ttyACM1` can not be fixed by home assistant or hassio. Most likely it will never be fixed, because its not a bug, but its a feature ;) it comes from the way udev handles devices. AFAIK it has something to do with udev handling devices parallel and thus its not clear what device will be ready first. 

However  `/dev/serial` is the right way to go, since it is there to be a persistent symlink to you deice. Now my problem is, that I updated from 66 -> 68 today and now, all devices under `/dev/serial` can't be found anymore. Anybody has the same issue? 
I checked, if I change back to `/dev/ttyUSBX` HA finds the devices. 
I run hassio on an x86 box and not a raspberry, but I doubt that is the reason.

**Comment by epeome5** [comment] 2018-05-30 21:36
I have this problem as well. I got it when updsting to 0.70.0. I have hass.io installed on a raspberry.

**Comment by deisi** [comment] 2018-05-31 06:32
Ah forgot about this. In my Case ist was due to a kernel update of the Arch Linux box. After a reboot of the host everything was just fine.

**Comment by epeome5** [comment] 2018-05-31 07:19
I have rebootet plenty of times. It seemes it doesn't help for mee. Have to wait and see if there's an update soon that fix the problem.

Thank you!

**Comment by deisi** [comment] 2018-05-31 10:28
I dont think this will haben. USB devices are passed through to the docker container using the privileged mode. If it is not working for you, it is either a config problem or a problem of your specific setup due to stuff like in my case. That was a kernel update that was not fully done. I think it's unlikely that there is something wrong on the large scale that would need fixing.

**Comment by epeome5** [comment] 2018-05-31 10:51
Ah ok, it shouldn't be a config problem since i havn't changed the config at all, it just stoped working after the last update.

And the setup shouldn't be a problem either since it worked before the update. Maby it's something, like the kernel, that wasn't fully done. But since its not working after multiple restarts i don't know. Maby i should tyr reinstall hassio.

**Comment by robhuls** [comment] 2018-06-01 19:44
I upgraded my installation to 0.70 and now the 'fix' using /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XSUJYH-if00-port0 stopped working. Guessing the ttyUSB number also seems have stopped working, so now it seems I don't have any working option left :-(

**Comment by epeome5** [comment] 2018-06-01 20:18
Oh meeeen!
That's not cool, what if you try to use ttyACMinstead? That's what i use and that works for mee, exept that i can't reboot the system since they change number then.

**Comment by robhuls** [comment] 2018-06-01 20:32
I have it working again, removed the devices, inserted them again and looked at the ttyUSB numbers for the configuration. The /dev/serial/.... links seem to have stopped working though, although I can see them. I have no time to debug further at the moment, I have to go on vacation (no home automation in the 1 m2 tent ;-) )

**Comment by epeome5** [comment] 2018-06-01 20:48
Yes! That correct, you hav to disconnect atleast one of them, I usually disconnect the one that in my config file have the number ttyACM1 and leave the one called ttyACM0. That works.

Vacation sounds nice, but a 1 m2 tent sounds awfully cramped =). I wish you vacation, where are you going?

**Comment by epeome5** [comment] 2018-06-29 19:41
After the latest update (0.27.0) serial/by-id/ has started working again. Yay!

**Comment by marcgarciamarti** [comment] 2018-08-26 09:56
@robhuls and @jonand could you be a little more specific/verbose on how you got this under control? I so far managed to ssh into the host but I'm not sure how to finally be able to solve it. I would appreciate that as this problem really renders part of my system useless when it shows up.

**Comment by robhuls** [comment] 2018-08-26 18:00
I didn't. When it gets messed up, I just restart HAS until it works. It hardly ever need more than 1 restart.

**Comment by marcgarciamarti** [comment] 2018-08-26 18:48
I’m pretty new to github but is there anyway I can bump or vote to further support the need to address this? I have two USB dongles and it really is a mess. Will look into udev rules but I’m not a Linux expert myself either :(

**Comment by marcgarciamarti** [comment] 2018-08-26 18:49
@epeome5, could you be a little more verbose on what you do and where?

**Comment by marcgarciamarti** [comment] 2018-08-26 20:59
@epeome5 of course! many thanks in advance! :)

**Comment by epeome5** [comment] 2018-08-27 15:31
I tried to ad the code as a code, but everything was added in a single line without line breakes and indentation for the yaml code.

**Comment by epeome5** [comment] 2018-08-27 15:36
And yeah, one other thing, you SSH into the host at your own risk. You'll find info about it here:
[https://developers.home-assistant.io/docs/en/hassio_debugging.html](url)

**Comment by marcgarciamarti** [comment] 2018-08-27 19:52
@epeome5 thanks a million for that. My two devices are one Z-stick gen 5 and CC2531. I've just configured the system as per the example above and the add-on relying on CC2531 does not seem to like receiving one attribute in the /dev/serial/by-id/ format. I just contacted the developer and ask if the path difference could be the problem. I did configure the zwave part as per your suggestion and it seems Home Assistant is ok with it because it passed the configuration check. 

As I can't yet configure my 2 dongles propperly, I can't declare victory just yet. Once I figure out the open loop I will report back. In the mean time, many many thanks again for your help and for taking the time to help me :)

**Comment by epeome5** [comment] 2018-08-27 21:50
What does your code look like?

**Comment by pvizeli** [comment] 2018-08-28 15:02
You can provide a udev rules in home-assistant container... that is the simple way.

-> home-assistant/hassio-homeassistant

**Comment by epeome5** [comment] 2018-08-28 16:46
@pvizeli Thanks! How do you do that I Hassio? When i google it I only find that it doesn't work in Hassio. 

I do like simple ways!

**Comment by marcgarciamarti** [comment] 2018-08-28 19:46
@epeome5 the add-on I'm currently having issues with is zigbee2mqtt https://github.com/Koenkk/zigbee2mqtt which is an amazing contribution to the project. 

My devices look like this

```
~ # cd /dev/serial/by-id/
/dev/serial/by-id # ls -l
lrwxrwxrwx    1 root     root            13 Aug 26 21:11 usb-0658_0200-if00 -> ../../ttyACM0
lrwxrwxrwx    1 root     root            13 Aug 26 21:34 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0012022476-if00 -> ../../ttyACM1

```

and  I simply configured both the configuration.yaml file as per your suggestion above, and set the corresponding parameter in the add-on configuration of zigbee2mqtt.

@pvizeli I fully support @epeome5 there: is there a simpler way with hassio than logging into the host and copying the device id?

**Comment by epeome5** [comment] 2018-08-28 20:16
@marcgarciamarti So in your config-file it looks something like this?

```
zigbee:
  device: /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0012022476-if00
  baud: xxx
```

**Comment by epeome5** [comment] 2018-08-28 20:39
ok,
When I googlade, I saw that there is a separate configuration.yaml file for zigbee2mqtt, I did not know that. But it almost looks like when you're adding it right in the hass config file directly.

Perhaps they have not implemented the by-id functionality in the extension yet.

**Comment by marcgarciamarti** [comment] 2018-08-28 20:43
yes, there is a configuration.yaml file for the add-on but whatever gets added in the configuration part on the add-on overwrites what is in the configuration file. This is the issue I opened: https://github.com/Koenkk/zigbee2mqtt/issues/311

**Comment by marcgarciamarti** [comment] 2018-09-16 20:41
@pvizeli could you be a little more specific on how to find information for understanding your suggestion:

> You can provide a udev rules in home-assistant container... that is the simple way

Thank you! :)

**Comment by Liquidmasl** [comment] 2018-09-17 04:27
i have currently a simmilar problem, my rfxtrx module stopped working by iteself, overnight (i still dont get how) and it seems it is because ttyACM1 kinda stopped working (directory not found)

i changed it to ttyUSB0 but now i get a stacktrace i cannot comprehend

```
Error during setup of component rfxtrx
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/rfxtrx.py", line 101, in setup
    rfx_object = rfxtrxmod.Connect(device, None, debug=debug)
  File "/usr/local/lib/python3.6/site-packages/RFXtrx/__init__.py", line 718, in __init__
    self.transport = transport_protocol(device, debug)
  File "/usr/local/lib/python3.6/site-packages/RFXtrx/__init__.py", line 601, in __init__
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/RFXtrx/__init__.py", line 606, in connect
    self.serial = serial.Serial(self.port, 38400, timeout=0.1)
  File "/usr/local/lib/python3.6/site-packages/serial/serialutil.py", line 182, in __init__
    self.open()
  File "/usr/local/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self._update_dtr_state()
  File "/usr/local/lib/python3.6/site-packages/serial/serialposix.py", line 595, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
OSError: [Errno 5] I/O error
```

i also tried using you way of getting serial ID, but using SSH and `ls -al /dev/serial/by-id` just gives me 
`ls: /dev/serial/by-id: No such file or directory`

i am googling and searching for houres now and i cant find any solution. sadly i am not as advanced in linux or PI stuff, thats why i used hass.io.
and it worked fine the past 6 months or so, i just stopped working a few days back sadly.

**Comment by marcgarciamarti** [comment] 2018-09-17 04:58
@liquidmasi please make sure you do a backup before proceeding. Once you’ve got your backup in place follow the steps found here https://developers.home-assistant.io/docs/en/hassio_debugging.html in order to gain access to the host. Be very careful not to modify anything or you could render your system useless. Accessing the host will enable browsing the devices by-id. Report back if you still can’t find your device.

**Comment by marcgarciamarti** [comment] 2018-10-14 17:55
> @pvizeli could you be a little more specific on how to find information for understanding your suggestion:
> 
> > You can provide a udev rules in home-assistant container... that is the simple way
> 
> Thank you! :)

@pvizeli could you please shed some light on your suggestion above? I still haven managed to solve this and everytime I reboot the system, it really is a nightmare :(

**Comment by sholzmayer** [comment] 2018-10-23 11:58
@pvizeli I'm also having those "nightmares" ;) Because the `udev status` says something about that udev is not supported in [docker] containers (in the addon).

`root@f7cf6bfd-myaddon:/# /etc/init.d/udev status
[warn] udev does not support containers, not started ... (warning).`

In home assistant itself udev is working correctly and outputs the udev-events via `udevadm monitor`. Any idea how i can give the correct permissions into the addon?

**Closed** 2019-04-23 13:41 UTC
Labels: wontfix
