### ISSUE TITLE
0.69.1 Hassio tab not working...

### ISSUE THREAD

**Issue by mattlward** [home-assistant/hassio#489] opened 2018-05-30 16:36 UTC
Please disregard... appears to be a firefox issue!  Updating to 70.0 now!

I have lost all data in the Hassio tab.  I do not see my addons, no tabs across the top for system or other things that have been there.  

In the last few releases I have had to refresh the screen to populate it, now a refresh does not bring the screens up...

I am running on an RPi 2.

I have restarted Hassio and rebooted the Pi.  The problem is persistent.  In fact a shift-reload results in a blank screen except for the left menu.  Browser is Firefox. 

![image](https://user-images.githubusercontent.com/8540074/40734426-0a2af61a-63fe-11e8-910a-680163dda3d2.png)

**Comment by messismore** [comment] 2018-05-30 16:56
I have the same issue. Reboot did not help unfortunately.

**Comment by TheCrey** [comment] 2018-05-30 19:10
Have the same issue with safari and all other browsers. 
How would one do the update now without the hassio frame ? As I am still on 0.69.1

Regards

**Comment by metbril** [comment] 2018-05-30 19:17
> How would one do the update now without the hassio frame ? As I am still on 0.69.1

Chrome appears to be working. You can go to the hass.io tab frame there and upgrade.

**Comment by ciotlosm** [comment] 2018-05-30 19:17
Navigate manually to https://<your DNS>/hassio/dashboard

**Comment by TheCrey** [comment] 2018-05-30 19:21
HI, 

Chrome does work, thanks for that. 

Thanks, will upgrade then if the issue is solved with this

**Comment by ciotlosm** [comment] 2018-05-31 06:39
@mattlward it's mentioned in the latest release notes for Home Assistant that Firefox still have some issues. https://www.home-assistant.io/blog/2018/05/27/release-70/#

>  Right now it looks like Firefox is still having some issues running the Hass.io panel. We’re working on releasing a fix for that soon.

**Comment by messismore** [comment] 2018-05-31 07:51
It‘s nit working in Safari (macOS and iOS) either.

**Comment by tomlut** [comment] 2018-05-31 14:47
Not Just firefox. This problem is also evident in IE, Edge, Safari and the iOS app. Uninstalling/reinstalling (in the case of the app) clearing history and cache (in the case of the web browsers) makes no difference.
Chrome is the only browser that the hassio tab shows up in.

**Comment by danielwelch** [comment] 2018-06-01 15:16
Yep, this is not fixed in Safari desktop, nor on the iOS app, mobile Safari, or mobile iOS Chrome (all of which I'm guessing are related).

**Comment by ciotlosm** [comment] 2018-06-01 15:26
@c727 should this item go here or in home-assistant-polymer repo?

**Comment by c727** [comment] 2018-06-01 17:22
Release notes say that Firefox is broken atm...

For other stuff check https://github.com/home-assistant/home-assistant-polymer/issues and provide detailed information (Browser, OS, Error logs)

**Closed by c727** 2018-06-01 17:22 UTC
