### ISSUE TITLE
Only available offline TTS (pico tts) broken on hassio

### ISSUE THREAD

**Issue by rradar** [home-assistant/hassio#1381] opened 2019-11-22 16:12 UTC
**Home Assistant release with the issue:**

0.102

**Operating environment (HassOS/Generic):**

- Tried with the offical hassio image for raspberry 3
- with hassio install on raspbian lite (also on a raspberry 3)
- and a hassio install on a generic linux machine (debian 9 on amd64)

Three times no luck

**Description of problem:**

Even picotts is installed on the base system (for example on raspian lite or debian 9) the component can't come up in home assistant (hassio based). I'm not sure if there is any (special) step needed which is not written in the docs (https://www.home-assistant.io/components/picotts/) or that picotts is just broken on hassio?

**Additional information:**

+1 for cloud free tts, https://github.com/home-assistant/home-assistant/issues/24749

**Comment by frenck** [comment] 2019-11-22 18:54
Duplicate of home-assistant/home-assistant#24749, which is a more fitting location.

**Closed by frenck** 2019-11-22 18:54 UTC
