### ISSUE TITLE
DNS resolution succeeds on host but fails in containers

### ISSUE THREAD

**Issue by nhorvath** [home-assistant/hassio#1236] opened 2019-08-17 13:00 UTC
**Home Assistant release with the issue:**

0.97.2

**Operating environment (HassOS/Generic):**

hassio > os info
board: ova
version: "2.12"
version_cli: "12"
version_cli_latest: "12"
version_latest: "2.12"

Running in x86_64 openbox vm

**Supervisor logs:**

```
19-10-18 06:42:46 INFO (MainThread) [__main__] Initialize Hass.io setup
19-10-18 06:42:46 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/amd64-hassio-supervisor with version 179
19-10-18 06:42:46 INFO (MainThread) [__main__] Setup HassIO
19-10-18 06:42:46 INFO (SyncWorker_2) [hassio.docker.interface] Attach to homeassistant/amd64-hassio-dns with version 1
19-10-18 06:42:46 INFO (MainThread) [hassio.dns] Update resolv from Supervisor
19-10-18 06:42:46 INFO (MainThread) [hassio.misc.forwarder] Start DNS port forwarding to 172.30.32.3
19-10-18 06:42:46 INFO (MainThread) [hassio.dns] Start CoreDNS plugin
19-10-18 06:42:46 INFO (SyncWorker_1) [hassio.docker.interface] Clean hassio_dns application
19-10-18 06:42:46 INFO (SyncWorker_1) [hassio.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 1
19-10-18 06:42:46 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.systemd1 on /org/freedesktop/systemd1
19-10-18 06:42:46 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
19-10-18 06:42:46 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.hostname1 on /org/freedesktop/hostname1
19-10-18 06:42:46 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
19-10-18 06:42:46 INFO (MainThread) [hassio.utils.gdbus] Introspect de.pengutronix.rauc on /
19-10-18 06:42:46 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: de.pengutronix.rauc - /
19-10-18 06:42:46 INFO (MainThread) [hassio.host.info] Update local host information
19-10-18 06:42:46 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
19-10-18 06:42:46 INFO (MainThread) [hassio.host.services] Update service information
19-10-18 06:42:46 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
19-10-18 06:42:46 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
19-10-18 06:42:46 INFO (MainThread) [hassio.host.services] Reload local service hassos-apparmor.service
19-10-18 06:42:46 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
19-10-18 06:42:46 INFO (SyncWorker_0) [hassio.docker.interface] Attach to homeassistant/qemux86-64-homeassistant with version 0.97.2
19-10-18 06:42:46 INFO (MainThread) [hassio.hassos] Detect HassOS 2.12 on host system
19-10-18 06:42:46 INFO (SyncWorker_4) [hassio.docker.hassos_cli] Found HassOS CLI homeassistant/amd64-hassio-cli with version 12
19-10-18 06:42:47 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/core repository
19-10-18 06:42:47 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/cebe7a76 repository
19-10-18 06:42:47 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/15ef4d2f repository
19-10-18 06:42:47 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/a0d7b954 repository
19-10-18 06:42:47 INFO (MainThread) [hassio.store] Load add-ons from store: 63 all - 63 new - 0 remove
19-10-18 06:42:47 INFO (MainThread) [hassio.addons] Found 12 installed add-ons
19-10-18 06:42:47 INFO (SyncWorker_8) [hassio.docker.interface] Attach to homeassistant/amd64-addon-configurator with version 3.4
19-10-18 06:42:47 INFO (SyncWorker_6) [hassio.docker.interface] Attach to homeassistant/amd64-addon-letsencrypt with version 3.0
19-10-18 06:42:47 INFO (SyncWorker_2) [hassio.docker.interface] Attach to homeassistant/amd64-addon-ssh with version 6.2
19-10-18 06:42:47 INFO (SyncWorker_7) [hassio.docker.interface] Attach to hassioaddons/sonweb-amd64 with version v0.8.1
19-10-18 06:42:47 INFO (SyncWorker_5) [hassio.docker.interface] Attach to hassioaddons/ftp-amd64 with version v3.0.2
19-10-18 06:42:47 INFO (SyncWorker_1) [hassio.docker.interface] Attach to sabeechen/hassio-google-drive-backup-amd64 with version 0.98.2
19-10-18 06:42:47 INFO (SyncWorker_3) [hassio.docker.interface] Attach to homeassistant/amd64-addon-mosquitto with version 5.0
19-10-18 06:42:47 INFO (SyncWorker_4) [hassio.docker.interface] Attach to esphome/esphome-hassio-amd64 with version 1.13.6
19-10-18 06:42:47 INFO (SyncWorker_0) [hassio.docker.interface] Attach to hassioaddons/traccar-amd64 with version v0.5.2
19-10-18 06:42:47 INFO (SyncWorker_9) [hassio.docker.interface] Attach to hassioaddons/unifi-amd64 with version v0.11.0
19-10-18 06:42:47 INFO (SyncWorker_6) [hassio.docker.interface] Attach to hassioaddons/motioneye with version v0.5.3
19-10-18 06:42:47 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
19-10-18 06:42:47 INFO (MainThread) [hassio.snapshots] Found 7 snapshot files
19-10-18 06:42:47 INFO (MainThread) [hassio.discovery] Load 1 messages
19-10-18 06:42:47 INFO (MainThread) [hassio.ingress] Load 0 ingress session
19-10-18 06:42:47 INFO (MainThread) [__main__] Run Hass.io
19-10-18 06:42:47 INFO (MainThread) [hassio.api] Start API on 172.30.32.2
19-10-18 06:42:47 INFO (MainThread) [hassio.addons] Phase 'initialize' start 0 add-ons
19-10-18 06:42:47 INFO (MainThread) [hassio.addons] Phase 'system' start 2 add-ons
19-10-18 06:42:47 WARNING (MainThread) [hassio.addons.validate] Unknown options ipv6
19-10-18 06:42:47 INFO (SyncWorker_0) [hassio.docker.addon] Start Docker add-on hassioaddons/sonweb-amd64 with version v0.8.1
19-10-18 06:42:47 INFO (SyncWorker_1) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-mosquitto with version 5.0
19-10-18 06:42:48 INFO (MainThread) [hassio.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
19-10-18 06:42:48 INFO (MainThread) [hassio.discovery] Send discovery to Home Assistant mqtt from core_mosquitto
19-10-18 06:42:48 ERROR (MainThread) [hassio.homeassistant] Error on call https://172.30.32.1:8123/api/: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
19-10-18 06:42:48 INFO (MainThread) [hassio.discovery] Discovery 537d5227471d45a3b963d070823436e9 mesage ignore
19-10-18 06:42:49 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_sonweb
19-10-18 06:42:52 INFO (MainThread) [hassio.addons] Phase 'services' start 6 add-ons
19-10-18 06:42:53 WARNING (MainThread) [hassio.addons.validate] Unknown options name
19-10-18 06:42:53 WARNING (MainThread) [hassio.addons.validate] Unknown options guest
19-10-18 06:42:53 WARNING (MainThread) [hassio.addons.validate] Unknown options map
19-10-18 06:42:53 ERROR (SyncWorker_8) [hassio.docker] Can't create container from addon_core_samba: 404 Client Error: Not Found ("No such image: homeassistant/amd64-addon-samba:8.1")
19-10-18 06:42:53 INFO (SyncWorker_6) [hassio.docker.addon] Start Docker add-on hassioaddons/traccar-amd64 with version v0.5.2
19-10-18 06:42:53 INFO (SyncWorker_0) [hassio.docker.addon] Start Docker add-on hassioaddons/ftp-amd64 with version v3.0.2
19-08-17 12:47:22 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
```

**Description of problem:**
Name resolution of all my localdomain ".horvath" machines is failing. If I login to hassio with ssh -p 22222 nslookup succeeds just fine and /etc/resolv.conf is correct. Running docker exec on my homeassistant container and running nslookup fails and my homeassistant logs are full of name resolution errors.

**Comment by nhorvath** [comment] 2019-08-17 13:31
See discussion in https://github.com/home-assistant/hassio/issues/1231

**Comment by nhorvath** [comment] 2019-08-17 15:35
@frenck I know you are working on it but I wanted to provide this observation:
After using `hassio dns options --servers dns://192.168.75.1` and rebooting my `hassio dns info` looks like this:
```
core-ssh:~# hassio dns info
host: 172.30.32.3
latest_version: "1"
servers:
- dns://192.168.75.1
version: "1"
```
corefile still has all 3
```
# docker exec -it hassio_dns /bin/bash
bash-5.0# cat corefile 
.:53 {
    log
    hosts /config/hosts {
        fallthrough
    }
    forward . dns://192.168.75.1 dns://8.8.8.8 dns://1.1.1.1 {
        health_check 10s
    }
}
```
and dns appears to use them in a round-robin fashion
```
core-ssh:~# ping htpc.horvath
ping: bad address 'htpc.horvath'
core-ssh:~# ping htpc.horvath
PING htpc.horvath (192.168.75.21): 56 data bytes
64 bytes from 192.168.75.21: seq=0 ttl=63 time=0.466 ms
64 bytes from 192.168.75.21: seq=1 ttl=63 time=0.232 ms
64 bytes from 192.168.75.21: seq=2 ttl=63 time=0.149 ms
^C
--- htpc.horvath ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.149/0.282/0.466 ms
core-ssh:~# ping htpc.horvath
ping: bad address 'htpc.horvath'
core-ssh:~# ping htpc.horvath
PING htpc.horvath (192.168.75.21): 56 data bytes
64 bytes from 192.168.75.21: seq=0 ttl=63 time=0.704 ms
64 bytes from 192.168.75.21: seq=1 ttl=63 time=0.450 ms
^C
--- htpc.horvath ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.450/0.577/0.704 ms
```

**Comment by frenck** [comment] 2019-08-17 15:39
I know, @nhorvath, see #1238 ;)

**Comment by frenck** [comment] 2019-08-18 07:15
Closing this as a duplicate of #1231

**Closed by frenck** 2019-08-18 07:15 UTC
