### ISSUE TITLE
Add support for Docker repository authentication

### ISSUE THREAD

**Issue by Eisler** [home-assistant/hassio#647] opened 2018-08-14 14:13 UTC
since it is possible to add private docker repositories ( #564 ) it now only fails due to authentication. 
Is there a simple solution?

`18-08-13 11:26:19 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/raspberrypi3-64-homeassistant docker application
18-08-13 11:26:21 INFO (SyncWorker_1) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-64-homeassistant with version 0.75.1
18-08-13 11:27:32 INFO (MainThread) [hassio.homeassistant] Detect a running HomeAssistant instance
18-08-13 11:27:32 INFO (MainThread) [hassio.addons] Startup application run 0 addons
18-08-13 11:27:32 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
18-08-13 11:27:32 INFO (MainThread) [hassio.core] Hass.io is up and running
18-08-13 11:27:53 INFO (SyncWorker_10) [hassio.docker.interface] Pull image registry.gitlab.com/eisler/test/testdocker tag armv7.
18-08-13 11:27:55 ERROR (SyncWorker_10) [hassio.docker.interface] Can't install registry.gitlab.com/eisler/test/testdocker:armv7 -> 500 Server Error: Internal Server Error ("Get https://registry.gitlab.com/v2/eisler/test/testdocker/manifests/armv7: denied: access forbidden").
`

**Comment by frenck** [comment] 2018-08-14 15:18
Duplicate of #646.

**Closed by frenck** 2018-08-14 15:18 UTC
